### ISSUE TITLE
goto def not working

### ISSUE THREAD

**Issue by markreg** [ironcladlou/GoTools#122]
Goto definition doesn't seem to work as expected. I moved over from GoSublime since it was having the same issue. Just to be sure, does this feature allow me to right click or hit `ctrl+g` and open another file and/or jump the cursor to the place where the type is defined?

As of no `Goto definition` option shows up nor does `ctrl+g` work as I thought it would.

Any suggestions? I think I'm missing something obvious here.

**Comment by stevekuznetsov** [comment]
In case there's some keybinding issue or collision, try sticking it on another key - I have in my default keymap

```json
[
	{ "keys": ["ctrl+shift+z"], "command": "gotools_goto_def"},
]
```

This works fine for me. 

You also must have the correct `${GOPATH}` set in order for the `oracle` to work.

**Comment by ironcladlou** [comment]
If in doubt, add this to your GoTools settings:

```json
 "debug_enabled": true
```

Then watch the Sublime console while running the `gotools_goto_def` command and see what you get.

**Comment by ironcladlou** [comment]
I also highly recommend using the `godef` backend rather than `oracle` if your project is of nontrivial size.

**Comment by markreg** [comment]
Unfortunately it still doesn't work. `Goto definition` doesn't show up in the right click menu and when I execute the keyboard shortcut i get this debug output in sublime's console:

```
GoTools: DEBUG: spawning process...
GoTools: DEBUG: 	command:     c:\go\path\bin\godef.exe -f C:\Users\Admin\repo\src\main.go -o 701
GoTools: DEBUG: 	environment: {'TEMP': 'C:\\Users\\Admin\\AppData\\Local\\Temp', 'SYSTEMROOT': 'C:\\Windows', 'SESSIONNAME': 'Console', 'COMPUTERNAME': 'MY-PC', 'APPDATA': 'C:\\Users\\Admin\\AppData\\Roaming', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'PATH': 'C:\\Go\\bin', '__COMPAT_LAYER': 'DisableUserCallbackException', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'WINDIR': 'C:\\Windows', 'PUBLIC': 'C:\\Users\\Public', 'ULTRAMON_LANGDIR': 'C:\\Program Files\\UltraMon\\Resources\\en', 'WINDOWS_TRACING_LOGFILE': 'C:\\BVTBin\\Tests\\installpackage\\csilogfile.log', 'SYSTEMDRIVE': 'C:', 'NUMBER_OF_PROCESSORS': '8', 'PROGRAMDATA': 'C:\\ProgramData', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'GOPATH': 'c:\\go\\path', 'HOMEDRIVE': 'C:', 'LOCALAPPDATA': 'C:\\Users\\Admin\\AppData\\Local', 'OS': 'Windows_NT', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'USERDOMAIN': 'MY-PC', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROGRAMFILES': 'C:\\Program Files', 'FP_NO_HOST_CHECK': 'NO', 'USERNAME': 'Admin', 'USERPROFILE': 'C:\\Users\\Admin', 'HOMEPATH': '\\Users\\Admin', 'WINDOWS_TRACING_FLAGS': '3', 'PROCESSOR_LEVEL': '6', 'LOGONSERVER': '\\\\MY-PC', 'GOROOT': 'C:\\Go\\', 'PROCESSOR_REVISION': '3a09', 'TMP': 'C:\\Users\\Admin\\AppData\\Local\\Temp', 'PROCESSOR_ARCHITECTURE': 'AMD64'}
GoTools: DEBUG: process returned (2) in 0 seconds
GoTools: DEBUG: stderr:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x4bac69]

goroutine 5 [running]:
github.com/rogpeppe/godef/go/ast.(*ImportSpec).End(0xc082005040, 0xc082005040)
	c:/go/path/src/github.com/rogpeppe/godef/go/ast/ast.go:791 +0x9
main.findIdentifier.func2.1(0x3c4600, 0xc082005040, 0x0)
	c:/go/path/src/github.com/rogpeppe/godef/godef.go:198 +0xfd
main.FVisitor.Visit(0xc0820aaea0, 0x3c4600, 0xc082005040, 0x0, 0x0)
	c:/go/path/src/github.com/rogpeppe/godef/godef.go:284 +0x47
github.com/rogpeppe/godef/go/ast.Walk(0x3c4c68, 0xc0820aaea0, 0x3c4600, 0xc082005040)
	c:/go/path/src/github.com/rogpeppe/godef/go/ast/walk.go:52 +0x5d
github.com/rogpeppe/godef/go/ast.Walk(0x3c4c68, 0xc0820aaea0, 0x3c4cf0, 0xc082006b80)
	c:/go/path/src/github.com/rogpeppe/godef/go/ast/walk.go:329 +0x1f9a
github.com/rogpeppe/godef/go/ast.walkDeclList(0x3c4c68, 0xc0820aaea0, 0xc082096800, 0x43, 0x80)
	c:/go/path/src/github.com/rogpeppe/godef/go/ast/walk.go:38 +0xdc
github.com/rogpeppe/godef/go/ast.Walk(0x3c4c68, 0xc0820aaea0, 0x3c4c90, 0xc08206c800)
	c:/go/path/src/github.com/rogpeppe/godef/go/ast/walk.go:351 +0x29da
main.findIdentifier.func2(0xc0820ae970, 0xc082010780, 0xc08206c800)
	c:/go/path/src/github.com/rogpeppe/godef/godef.go:204 +0x10b
created by main.findIdentifier
	c:/go/path/src/github.com/rogpeppe/godef/godef.go:206 +0xa6

goroutine 1 [chan receive]:
main.findIdentifier(0xc08206c800, 0x2bd, 0x0, 0x0)
	c:/go/path/src/github.com/rogpeppe/godef/godef.go:207 +0xd6
main.main()
	c:/go/path/src/github.com/rogpeppe/godef/godef.go:101 +0x101a

```

This is my `go env`:

```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\go\path
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```
